version: "3.7"
services:
  api_service:
    ports:
      - 8080:8080
    build:
      context: .
    restart: always
    depends_on:
      - mysql
  mysql:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password